//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fpv_info.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fpv_info.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accessories.
        /// </summary>
        internal static string accessories_en {
            get {
                return ResourceManager.GetString("accessories_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Периферия.
        /// </summary>
        internal static string accessories_ru {
            get {
                return ResourceManager.GetString("accessories_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string add_en {
            get {
                return ResourceManager.GetString("add_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        internal static string add_ru {
            get {
                return ResourceManager.GetString("add_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Antennas.
        /// </summary>
        internal static string antennas_en {
            get {
                return ResourceManager.GetString("antennas_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Антенны.
        /// </summary>
        internal static string antennas_ru {
            get {
                return ResourceManager.GetString("antennas_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        internal static string back_en {
            get {
                return ResourceManager.GetString("back_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        internal static string back_ru {
            get {
                return ResourceManager.GetString("back_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Batteries.
        /// </summary>
        internal static string batteries_en {
            get {
                return ResourceManager.GetString("batteries_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Batteries/Chargers.
        /// </summary>
        internal static string batteries_group_en {
            get {
                return ResourceManager.GetString("batteries_group_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккумуляторы.
        /// </summary>
        internal static string batteries_group_ru {
            get {
                return ResourceManager.GetString("batteries_group_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккумуляторы.
        /// </summary>
        internal static string batteries_ru {
            get {
                return ResourceManager.GetString("batteries_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuselage.
        /// </summary>
        internal static string body_en {
            get {
                return ResourceManager.GetString("body_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фюзеляж.
        /// </summary>
        internal static string body_ru {
            get {
                return ResourceManager.GetString("body_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cameras.
        /// </summary>
        internal static string cameras_en {
            get {
                return ResourceManager.GetString("cameras_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Камеры.
        /// </summary>
        internal static string cameras_ru {
            get {
                return ResourceManager.GetString("cameras_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chargers.
        /// </summary>
        internal static string chargers_en {
            get {
                return ResourceManager.GetString("chargers_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарядные.
        /// </summary>
        internal static string chargers_ru {
            get {
                return ResourceManager.GetString("chargers_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        internal static string date_en {
            get {
                return ResourceManager.GetString("date_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        internal static string date_ru {
            get {
                return ResourceManager.GetString("date_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string delete_en {
            get {
                return ResourceManager.GetString("delete_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string delete_ru {
            get {
                return ResourceManager.GetString("delete_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description (eng.).
        /// </summary>
        internal static string descriptionEn_en {
            get {
                return ResourceManager.GetString("descriptionEn_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание (англ.).
        /// </summary>
        internal static string descriptionEn_ru {
            get {
                return ResourceManager.GetString("descriptionEn_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description (ru.).
        /// </summary>
        internal static string descriptionRu_en {
            get {
                return ResourceManager.GetString("descriptionRu_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание (русский).
        /// </summary>
        internal static string descriptionRu_ru {
            get {
                return ResourceManager.GetString("descriptionRu_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        internal static string details_en {
            get {
                return ResourceManager.GetString("details_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробнее.
        /// </summary>
        internal static string details_ru {
            get {
                return ResourceManager.GetString("details_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string edit_en {
            get {
                return ResourceManager.GetString("edit_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        internal static string edit_ru {
            get {
                return ResourceManager.GetString("edit_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Electronics.
        /// </summary>
        internal static string electronics_en {
            get {
                return ResourceManager.GetString("electronics_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электроника.
        /// </summary>
        internal static string electronics_ru {
            get {
                return ResourceManager.GetString("electronics_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Events.
        /// </summary>
        internal static string events_en {
            get {
                return ResourceManager.GetString("events_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на События.
        /// </summary>
        internal static string events_ru {
            get {
                return ResourceManager.GetString("events_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event type.
        /// </summary>
        internal static string eventType_en {
            get {
                return ResourceManager.GetString("eventType_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип события.
        /// </summary>
        internal static string eventType_ru {
            get {
                return ResourceManager.GetString("eventType_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flight Controllers.
        /// </summary>
        internal static string fc_en {
            get {
                return ResourceManager.GetString("fc_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контроллеры.
        /// </summary>
        internal static string fc_ru {
            get {
                return ResourceManager.GetString("fc_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Frames.
        /// </summary>
        internal static string frames_en {
            get {
                return ResourceManager.GetString("frames_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рамы.
        /// </summary>
        internal static string frames_ru {
            get {
                return ResourceManager.GetString("frames_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Goggles.
        /// </summary>
        internal static string goggles_en {
            get {
                return ResourceManager.GetString("goggles_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очки, шлемы.
        /// </summary>
        internal static string goggles_ru {
            get {
                return ResourceManager.GetString("goggles_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lighting.
        /// </summary>
        internal static string light_en {
            get {
                return ResourceManager.GetString("light_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подсветка.
        /// </summary>
        internal static string light_ru {
            get {
                return ResourceManager.GetString("light_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Motors/Accessories.
        /// </summary>
        internal static string motors_accessories_en {
            get {
                return ResourceManager.GetString("motors_accessories_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВМГ.
        /// </summary>
        internal static string motors_accessories_ru {
            get {
                return ResourceManager.GetString("motors_accessories_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Motors.
        /// </summary>
        internal static string motors_en {
            get {
                return ResourceManager.GetString("motors_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Моторы.
        /// </summary>
        internal static string motors_ru {
            get {
                return ResourceManager.GetString("motors_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string name_en {
            get {
                return ResourceManager.GetString("name_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        internal static string name_ru {
            get {
                return ResourceManager.GetString("name_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name (eng.).
        /// </summary>
        internal static string nameEn_en {
            get {
                return ResourceManager.GetString("nameEn_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя (англ.).
        /// </summary>
        internal static string nameEn_ru {
            get {
                return ResourceManager.GetString("nameEn_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name (ru.).
        /// </summary>
        internal static string nameRu_en {
            get {
                return ResourceManager.GetString("nameRu_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя (русский).
        /// </summary>
        internal static string nameRu_ru {
            get {
                return ResourceManager.GetString("nameRu_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        internal static string next_en {
            get {
                return ResourceManager.GetString("next_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вперед.
        /// </summary>
        internal static string next_ru {
            get {
                return ResourceManager.GetString("next_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parts.
        /// </summary>
        internal static string parts_en {
            get {
                return ResourceManager.GetString("parts_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комплектующие.
        /// </summary>
        internal static string parts_ru {
            get {
                return ResourceManager.GetString("parts_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Path.
        /// </summary>
        internal static string path_en {
            get {
                return ResourceManager.GetString("path_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь.
        /// </summary>
        internal static string path_ru {
            get {
                return ResourceManager.GetString("path_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Propellers.
        /// </summary>
        internal static string props_en {
            get {
                return ResourceManager.GetString("props_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пропеллеры.
        /// </summary>
        internal static string props_ru {
            get {
                return ResourceManager.GetString("props_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Radio Systems.
        /// </summary>
        internal static string radiosystems_en {
            get {
                return ResourceManager.GetString("radiosystems_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Радио управление.
        /// </summary>
        internal static string radiosystems_ru {
            get {
                return ResourceManager.GetString("radiosystems_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other.
        /// </summary>
        internal static string rcother_en {
            get {
                return ResourceManager.GetString("rcother_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прочее.
        /// </summary>
        internal static string rcother_ru {
            get {
                return ResourceManager.GetString("rcother_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Receivers.
        /// </summary>
        internal static string receivers_en {
            get {
                return ResourceManager.GetString("receivers_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приемники.
        /// </summary>
        internal static string receivers_ru {
            get {
                return ResourceManager.GetString("receivers_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Servos.
        /// </summary>
        internal static string servos_en {
            get {
                return ResourceManager.GetString("servos_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервоприводы.
        /// </summary>
        internal static string servos_ru {
            get {
                return ResourceManager.GetString("servos_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title (eng.).
        /// </summary>
        internal static string titleEn_en {
            get {
                return ResourceManager.GetString("titleEn_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок (англ.).
        /// </summary>
        internal static string titleEn_ru {
            get {
                return ResourceManager.GetString("titleEn_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title (ru.).
        /// </summary>
        internal static string titleRu_en {
            get {
                return ResourceManager.GetString("titleRu_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок (русский).
        /// </summary>
        internal static string titleRu_ru {
            get {
                return ResourceManager.GetString("titleRu_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Transmitters.
        /// </summary>
        internal static string transmitters_en {
            get {
                return ResourceManager.GetString("transmitters_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Передатчики.
        /// </summary>
        internal static string transmitters_ru {
            get {
                return ResourceManager.GetString("transmitters_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video RX.
        /// </summary>
        internal static string videoreceivers_en {
            get {
                return ResourceManager.GetString("videoreceivers_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приемники.
        /// </summary>
        internal static string videoreceivers_ru {
            get {
                return ResourceManager.GetString("videoreceivers_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video TX.
        /// </summary>
        internal static string videotransmitters_en {
            get {
                return ResourceManager.GetString("videotransmitters_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Передатчики.
        /// </summary>
        internal static string videotransmitters_ru {
            get {
                return ResourceManager.GetString("videotransmitters_ru", resourceCulture);
            }
        }
    }
}
