// <auto-generated />
using fpv_info.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace fpv_info.Migrations
{
    [DbContext(typeof(PartsContext))]
    [Migration("20180120195534_Mg200118_2")]
    partial class Mg200118_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("fpv_info.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description_en");

                    b.Property<string>("Description_ru");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("fpv_info.Models.FileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alt");

                    b.Property<int?>("FlightControllerId");

                    b.Property<int?>("MotorId");

                    b.Property<string>("Name");

                    b.Property<int?>("PDBId");

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.HasIndex("FlightControllerId");

                    b.HasIndex("MotorId");

                    b.HasIndex("PDBId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("fpv_info.Models.FlightController", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description_en");

                    b.Property<string>("Description_ru");

                    b.Property<bool>("IsCompared");

                    b.Property<int?>("ManufacturerId");

                    b.Property<string>("Name_en");

                    b.Property<string>("Name_ru");

                    b.Property<float>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("FlightControllers");
                });

            modelBuilder.Entity("fpv_info.Models.Motor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description_en");

                    b.Property<string>("Description_ru");

                    b.Property<bool>("IsCompared");

                    b.Property<int?>("ManufacturerId");

                    b.Property<string>("Name_en");

                    b.Property<string>("Name_ru");

                    b.Property<float>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Motors");
                });

            modelBuilder.Entity("fpv_info.Models.PDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description_en");

                    b.Property<string>("Description_ru");

                    b.Property<bool>("IsCompared");

                    b.Property<int?>("ManufacturerId");

                    b.Property<string>("Name_en");

                    b.Property<string>("Name_ru");

                    b.Property<float>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("PDBs");
                });

            modelBuilder.Entity("fpv_info.Models.FileModel", b =>
                {
                    b.HasOne("fpv_info.Models.FlightController")
                        .WithMany("Images")
                        .HasForeignKey("FlightControllerId");

                    b.HasOne("fpv_info.Models.Motor")
                        .WithMany("Images")
                        .HasForeignKey("MotorId");

                    b.HasOne("fpv_info.Models.PDB")
                        .WithMany("Images")
                        .HasForeignKey("PDBId");
                });

            modelBuilder.Entity("fpv_info.Models.FlightController", b =>
                {
                    b.HasOne("fpv_info.Models.Company", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("fpv_info.Models.Motor", b =>
                {
                    b.HasOne("fpv_info.Models.Company", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");
                });

            modelBuilder.Entity("fpv_info.Models.PDB", b =>
                {
                    b.HasOne("fpv_info.Models.Company", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");
                });
#pragma warning restore 612, 618
        }
    }
}
